- name: Install software
  apt:
    name:
      - gnupg2
      - apt-transport-https
      - software-properties-common
    update_cache: yes

- name: Add repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgresql repository
  apt_repository:
    state: present
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    update_cache: yes
    filename: postgresql
    
- name: Set postgresql version if defined
  set_fact:
    postgresql_package: "postgresql-{{ postgresql_version }}"
  when: postgresql_version is defined

- name: Install postgresql
  apt:
    name: "{{ postgresql_package }}"
    state: present
    update_cache: yes