- name: Install software
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - wget
      - libbz2-dev
    update_cache: yes

- name: Create a directory for python3.10 archive
  ansible.builtin.file:
    path: /opt/python3.10
    state: directory
    mode: '0755'

- name: Get python3.10 archive and unarchive
  ansible.builtin.unarchive:
    src: https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz
    dest: /opt/python3.10
    remote_src: yes

- name: Run compiling
  shell: cd /opt/python3.10/Python-3.10.12 && ./configure --prefix=/usr/local --enable-optimizations --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"

- name: Run make
  shell: cd /opt/python3.10/Python-3.10.12 && make -j $(nproc)

- name: Run make uninstall
  shell: cd /opt/python3.10/Python-3.10.12 && make altinstall