- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Check config
  shell: "/usr/sbin/nginx -t"
  register: nginx_status

- name: Reload nginx
  service:
    name=nginx
    state=reloaded
  when: nginx_status.rc == 0