---
- name: Ping all servers
  hosts: all
  tasks:
  - name: Run ping
    ping:
      data: pong from Ansible
    register: ping_answer

  - name: Print answer
    debug:
      msg: "Return value from ping is '{{ping_answer.ping}}'"